version: 0.17.3.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
environment:
  CI: true

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

install:
  - npm install -g npm
  - npm --version
  - ps: Install-Product node LTS
  - node --version
  - dotnet --version

build_script:
- cmd: >-
    yarn build-ci

test: off

artifacts:
  - path: 'artifacts\*.nupkg'

deploy:
- provider: NuGet
  server: https://www.myget.org/F/graphql-dotnet/api/v2/package
  api_key:
    secure: +l1vfBMajn1WfmXkQ2LdILKxK4fQ5AHSnnU1kf11Bn1xRGUOTCdPhLwHx232piEn
  skip_symbols: true
  on:
    branch:
      - master
      - dev
      - instance
