version: 2.4.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: false
test: off

os: Visual Studio 2017

environment:
  CI: true

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: Install-Product node LTS
  - ps: choco install dotnetcore-sdk --no-progress --confirm --version 2.1.403
  - node --version
  - npm --version
  - dotnet --version

build_script:
- cmd: >-
    yarn build-ci


artifacts:
  - path: 'artifacts\*.nupkg'

deploy:
- provider: NuGet
  server: https://www.myget.org/F/graphql-dotnet/api/v2/package
  api_key:
    secure: +l1vfBMajn1WfmXkQ2LdILKxK4fQ5AHSnnU1kf11Bn1xRGUOTCdPhLwHx232piEn
  skip_symbols: false
  symbol_server: https://www.myget.org/F/graphql-dotnet/symbols/api/v2/package
  on:
    branch:
      - master
      - dev
