# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration. For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on:
  pull_request_target:
    types:
      - opened        # when PR is opened

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        sync-labels: ""
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
      continue-on-error: true
