name: Check if PR title contains [WIP]

on:
  pull_request:
    types: 
      - opened        # when PR is opened
      - edited        # when PR title is edited
      - synchronize   # when code is added
      - reopened      # when a closed PR is reopened

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Fail build if pull request title contains [WIP]
        if: ${{ contains(github.event.pull_request.title, '[WIP]') }} # This function is not case sensitive.
        run: |
          echo Warning! PR title '${{ github.event.pull_request.title }}' contains [WIP]. Remove [WIP] from the title when PR is ready.
          exit 1
